version: '3.8'
services:
  mongodb:
    image: mongo
    logging:
      driver: "none"
    ports:
      - "27017:27017"
  postgresql:
    image: postgres
    logging:
      driver: "none"
    environment:
      POSTGRES_DB: shopAppTS
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"

  app:
    container_name: node_api
    restart: always
    build: .
    working_dir: /app
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      DB_NAME: shopAppTS
      DB_USER: admin
      DB_PASSWORD: 1111
    depends_on:
      - postgresql
    command: >
      sh -c "npm run build && npm run start"
