version: '3.8'
services:
  mongodb:
    image: mongo
    logging:
      driver: "none"
    ports:
      - "27017:27017"
  app:
    container_name: node_api
    restart: on-failure
    build: .
    volumes:
      - ./src:/app/src
      - ./dist/js:/app/dist/js
    ports:
      - "3000:3000"
    command: >
      sh -c "npm run start"