### GET /products
GET http://localhost:3000/products

### POST /product
POST http://localhost:3000/product
Content-Type: application/json

{
  "category_id": 1,
  "name": "Product A",
  "price": 50.99
}

### PUT /product/:id
PUT http://localhost:3000/product/3
Content-Type: application/json

{
  "category_id": 4,
  "name": "Updated Product B",
  "price": 5
}

### PATCH /product/:id
PATCH http://localhost:3000/product/2
Content-Type: application/json

{
  "category_id": 2,
  "price": 60.99
}

### DELETE /product/:id
DELETE http://localhost:3000/product/2
